Repository shipwright-io/operator, pull requests merged in 2022-04, with the labels that each got.

#65 Reconcile Tekton in Separate Package
  controllers/shipwrightbuild_controller.go
  controllers/shipwrightbuild_controller_test.go
  pkg/tekton/tekton.go
  pkg/tekton/tekton_test.go
Labels: lgtm, kind/cleanup, approved, release-note-none

#66 Use Square Logo for Operator
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  config/manifests/bases/shipwright-operator.clusterserviceversion.yaml
Labels: kind/feature, lgtm, approved, release-note

#63 Remove former contributors
  OWNERS
Labels: lgtm, kind/cleanup, approved, release-note-none

#67 Deploy Shipwright Build v0.9.0
  Makefile
  README.md
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  cmd/operator/kodata/release.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/shipwright-operator.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  config/rbac/shipwright_build_aggregate_role.yaml
  config/rbac/shipwright_build_aggregate_role_binding.yaml
  docs/shipwrightbuild.md
Labels: kind/feature, kind/documentation, lgtm, approved, release-note

#68 Prepare release v0.9.0
  Makefile
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: kind/feature, lgtm, approved, release-note-none

#69 Use ko to render full image specifications into the operator bundle image
  .github/workflows/ci.yml
  Makefile
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/shipwright-operator.clusterserviceversion.yaml
  controllers/shipwrightbuild_controller_test.go
  docs/development/local-development.md
  docs/development/olm-development.md
  hack/check-git-status.sh
  hack/release.sh
  kodata/release.yaml
  main.go
Labels: kind/feature, lgtm, approved, release-note
