Repository shipwright-io/operator, pull requests merged in 2023-11, with the labels that each got.

#145 chore: Add CSV `spec.minKubeVersion`
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  config/manifests/bases/shipwright-operator.clusterserviceversion.yaml
Labels: kind/feature, size/XS, lgtm, approved, release-note

#164 Update operator-sdk to v1.18
  Makefile
  bundle.Dockerfile
  bundle/manifests/shipwright-operator-metrics-service_v1_service.yaml
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  hack/install-operator-sdk.sh
Labels: size/M, kind/dependency-change, lgtm, approved, release-note

#169 Skip EnvTest Tests
  Makefile
  controllers/suite_test.go
Labels: size/S, lgtm, kind/cleanup, approved, release-note-none

#163 Add Developer Guide
  DEVELOPMENT.md
  README.md
Labels: kind/documentation, size/M, lgtm, approved, release-note-none

#172 Operator should not delete CRDs
  controllers/default_test.go
  controllers/shipwrightbuild_controller.go
Labels: kind/bug, size/S, lgtm, approved, release-note

#144 Remove operatorhub from test catalog
  Makefile
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  docs/development/olm-development.md
  test/catalog/candidate/shipwright-operator-package.json
  test/catalog/operatorhubio/cert-manager-operator-bundle.json
  test/catalog/operatorhubio/cert-manager-operator-channel-candidate.json
  test/catalog/operatorhubio/cert-manager-operator-package.json
  test/catalog/operatorhubio/shipwright-operator-bundle.json
  test/catalog/operatorhubio/shipwright-operator-channel-alpha.json
  test/catalog/operatorhubio/tektoncd-operator-bundle.json
  test/catalog/operatorhubio/tektoncd-operator-channel-alpha.json
  test/catalog/operatorhubio/tektoncd-operator-package.json
Labels: size/L, lgtm, kind/cleanup, approved, release-note-none
