Repository shipwright-io/operator, pull requests merged in 2024-05, with the labels that each got.

#204 Truncate CRD Description Fields to 50 Characters
  controllers/shipwrightbuild_controller.go
  pkg/common/testdata/test-truncate-crd-field.yaml
  pkg/common/util.go
  pkg/common/util_test.go
Labels: kind/bug, size/L, lgtm, approved, release-note

#182 Source release.yaml from GitHub release
  bundle/manifests/shipwright-operator.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  config/rbac/shipwright_build_webhook_role.yaml
  config/rbac/shipwright_build_webhook_role_binding.yaml
  kodata/release.yaml
Labels: size/XXL, lgtm, kind/cleanup, approved, release-note

#207 Update GitHub Actions to Latest Versions
  .github/workflows/ci.yml
Labels: size/S, lgtm, kind/cleanup, approved, release-note-none
